version: "3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: db-postgres12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - 5431:5432

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: email@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 1010:80
    depends_on:
      - postgres
